api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/pnpm"
  id = "paketo-buildpacks/pnpm"
  name = "Paketo Buildpack for pnpm"
  version = "0.0.1"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pnpm/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "bin/build", "bin/detect", "bin/run"]
  [metadata.default-versions]
    pnpm = "9.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"